export default function PrivacyPolicy() {
  return (
    <div className="lg:px-32 md:px-16 px-8 pb-10 pt-32 md:pt-36">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="mb-4">
        The following Privacy Policy (hereinafter the “Policy”) governs the
        manner in which BizVibez, and its bodies corporate and affiliates
        (collectively known as “BizVibez”) collect, use, maintain and disclose
        personal information and explains how you can access your own personal
        information.
      </p>
      <p className="mb-4">
        This Policy is applicable to personal information and aggregated
        information we collect on this BizVibez website https://BizVibez.com/
        (hereinafter the “Website”), which must be read in conjunction with the
        Website’s Terms of Use.
      </p>
      <p className="mb-4">
        Where this Policy refers to “we”, “us” and “our” we mean BizVibez, and
        where this Policy refers to “you” and “your” we mean the user of the
        Website.
      </p>
      <p className="mb-4">
        You undertake, including but not limited to, that viewing, using the
        Website, obtaining any goods or services from us, you shall be deemed to
        agree to this Policy. Should you fail to comply with this Policy, then
        you must refrain from using or accessing the Website.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        1. Information Collection and Usage
      </h2>
      <p className="mb-4">
        While using our Website, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you. Therefore, we may gather two types of information about
        you:
      </p>
      <h3 className="text-xl font-medium mt-6 mb-2">
        (a) Personal information
      </h3>
      <p className="mb-4">
        Personal information including but not limited to, your name, address,
        phone number, email address, date of birth, and payment information,
        which may be collected from you when you voluntarily provide the same
        through the following methods, including but not limited to:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Registering and creating a membership account;</li>
        <li>
          Participating in surveys and other promotions available on the
          Website;
        </li>
        <li>
          Communicating with us through the Contact Us information provided on
          our Website or through the Customer Service Live Chat or via
          telephone;
        </li>
        <li>
          Interaction with us on our social media platforms (such as Facebook,
          Instagram, Twitter, LinkedIn) or Website;
        </li>
        <li>
          Other sources such as third parties where it is reasonably necessary
          for our normal business practices to do so.
        </li>
      </ul>
      <h3 className="text-xl font-medium mt-6 mb-2">
        (b) Aggregate information
      </h3>
      <p className="mb-4">
        Aggregate information is generated by BizVibez’s systems, which is not
        directly related to you personally. Whenever you interact with BizVibez
        Products and/or Services, we automatically receive and record
        information and data on our server logs from your browser or device,
        which may include your IP address, device identification “cookie”
        information (please see below under “Cookies and Tracking”), the type of
        browser and/or device you’re using to access our Services, and the page
        or feature you requested. BizVibez uses this data to improve our
        Products and/or Services – for example, we learn how to best design the
        Website for visitors and understand what Products and/or Services you
        may prefer, and we can use that knowledge to improve user experience for
        our customers.
      </p>
      <p className="mb-4">
        Failure to provide necessary personal information when requested may
        result in certain services not being available to you. BizVibez may
        collect additional information from you in relation to promotions, and
        also any information you provide when corresponding with BizVibez such
        as through Customer Service Live Chat, and participation in surveys.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        2. Disclosure of Information
      </h2>
      <p className="mb-4">
        BizVibez may disclose Personal Information about you provided you have
        granted authority for the following:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>
          To disclose with our affiliates worldwide, licensees, and joint
          venture partners for the purposes described in this Privacy Policy;
        </li>
        <li>
          Any information that it gathers about you to third parties for the
          purposes of providing you with services that you request;
        </li>
        <li>
          Aggregate tracking information and other information that does not
          personally identify you to third parties;
        </li>
        <li>
          Your personal information to third parties, when BizVibez believes in
          good faith that it is required to do so by law or legal process; or
        </li>
        <li>
          Your authorized personal information to third parties which shall be
          obtained at the time of collecting the information from you.
        </li>
      </ul>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        3. Use of Information
      </h2>
      <p className="mb-4">
        BizVibez shall use the personal information it collects:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>
          To verify your identity and assist you if you forget your password or
          login details for any of BizVibez’s registration services;
        </li>
        <li>To assist in providing the services requested by you;</li>
        <li>
          To provide further information to you about other websites and
          services which BizVibez considers may be of interest to you;
        </li>
        <li>
          For future marketing, promotional and publicity purposes, including to
          carry out direct marketing, market research and surveys;
        </li>
        <li>
          For internal purposes, development and administration of our sites,
          data analytics, and compliance with our legal obligations, policies
          and procedures;
        </li>
        <li>
          For ensuring that you are shown the information that is most relevant
          to you and your interests;
        </li>
        <li>
          To prevent and detect any misuse of, or fraudulent activities; and for
          any other use that you authorize.
        </li>
      </ul>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        4. Cookies and Tracking
      </h2>
      <p className="mb-4">
        This Website uses a “Cookies and Tracking” file that is transferred to
        your computer’s hard drive, which can identify details of your IP
        address, operating system (e.g. Microsoft Windows, Mac O/S, Linux),
        browser (e.g. Internet Explorer, Safari, Firefox, plus the version of
        the Browser), locale (to determine which country you are accessing the
        Website from), and other user information (e.g. your username).
      </p>
      <p className="mb-4">
        BizVibez may use the information generated by cookies to:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Track traffic patterns to and from the Website;</li>
        <li>
          Ensure any advertising is being shown to the most appropriate person;
          and enable you to enter the Website and use certain services and to
          visit registered user only areas of the Website.
        </li>
      </ul>
      <p className="mb-4">
        Should you wish to refuse to accept cookies, you may choose to disable
        it in your browser and/or delete cookies from your hard drive. It is not
        a necessity to have cookies turned on to use the Website however, you
        may require cookies to log on to the Website and to access personalized
        or secure content on the Website. Some web pages may not function
        properly should the cookies be disabled.
      </p>
      <p className="mb-4">
        BizVibez’s use of Google Analytics is in compliance with Google’s Terms
        of Service and this Privacy Policy. The information generated by Google
        Analytics, including the user’s IP address, shall be transmitted to and
        stored by Google on servers in the United States. Information collected
        through Google Analytics does not include and is not linked to any
        personal information. Google shall not share the collected information
        with other Google products and tools. Information collected permits
        evaluation of the use of this Website, analysis of user behavior, and
        improvement of the user’s experience with the Website. To obtain more
        information about how to opt out of Google Analytics at
        https://tools.google.com/dlpage/gaoptout.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        5. Content Providers, Advertisers and Partners
      </h2>
      <p className="mb-4">
        This Privacy Policy shall not apply to other third-party websites to
        which we may link, or to other companies or persons who may be listed as
        third-party contacts or suppliers on this Website. BizVibez is not
        responsible for the data collection practices, privacy policies, or the
        contents of other websites other than this Website, including any other
        websites that are accessible via a link from this Website. You should
        contact the operators of that particular website(s) directly should you
        wish to inquire about their privacy practices and policies before
        providing your personal information to any third party.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">6. Opting In and Out</h2>
      <p className="mb-4">
        Should BizVibez’s intended collection, use or disclosure of your
        personal information be outside the collection, use, or disclosure set
        out in this Privacy Policy, BizVibez shall provide you with the option
        to:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>
          Opt out and neither receive certain services nor participate in
          certain interactive areas; or
        </li>
        <li>
          Opt in to agree to be contacted by BizVibez in relation to certain
          matters such as notification of new features to the Websites, beta
          testing, or promotional activities.
        </li>
      </ul>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        7. Protecting Your Personal Information
      </h2>
      <p className="mb-4">
        The security of your personal information is important to BizVibez. We
        recognize industry standards and practice appropriate administrative,
        technical, and physical security safeguards to protect the personal
        information you provide on this Website against accidental, unlawful, or
        unauthorized destruction, loss, alteration, access, unauthorized
        disclosure, or use and other unlawful forms of processing. In order to
        protect your personal information, we use several security techniques
        including secure servers. All your personal information, including your
        credit card details, is encrypted before leaving your browser, using
        industrial-strength TLS 1.2, ECDHE_RSA with X25519, and AES_128_GCM.
      </p>
      <p className="mb-4">
        BizVibez uses VeriSign’s online payment gateway to provide secure
        authorization of credit card transactions over the internet. VeriSign,
        Inc. is a leading provider of digital trust services that enable
        internet users to more safely engage in e-commerce. VeriSign handles
        your complete credit card transaction with your bank and informs
        BizVibez regarding the authorized transaction. We do not log your credit
        card details on BizVibez’s servers or anywhere else on the internet.
      </p>
      <p className="mb-4">
        BizVibez shall keep these measures under review and enhance them from
        time to time as necessary. It is important for you to protect against
        unauthorized access to your login information, including your password.
        No method of transmission over the Internet, or method of electronic
        storage, is 100% secure, therefore, BizVibez shall not guarantee the
        absolute security of your personal information and shall not be held
        liable.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        8. Disclosure of Information Overseas
      </h2>
      <p className="mb-4">
        We may require to transfer your collected personal information to
        countries other than the country in which you originally provided the
        information. These countries may not have the same data protection laws
        as the country in which you provided the information. When we transfer
        your information to other countries, BizVibez shall protect that
        information as described in this Privacy Notice. We may also disclose
        your personal information as required or permitted by law to law
        enforcement agencies, regulatory authorities, and governments for
        security and customs purposes.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        9. Holding, Correcting and Updating Information
      </h2>
      <p className="mb-4">
        Your information shall be collected and managed for the purposes stated
        in this Privacy Policy. BizVibez may allow other third parties to have
        access to your information, but only for the purposes set out in this
        Privacy Policy. BizVibez shall take measures necessary to ensure that
        your information is treated securely and in accordance with this Privacy
        Policy.
      </p>
      <p className="mb-4">
        We offer you the ability to correct or change the information collected
        at any time and as often as necessary, with the exception of certain
        data fields which are restricted data fields and shall be marked as such
        on your account – for example, your country of residence. Where you wish
        to amend a restricted data field or if you have any questions about how
        BizVibez services work or regarding this Privacy Policy, please contact
        BizVibez Customer Service Live Chat team.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">10. Amendments</h2>
      <p className="mb-4">
        BizVibez reserves the right to change this Privacy Policy at any time
        and without providing you notice of such changes. You undertake that
        your continued use of the Website constitutes your acceptance of the
        modified Privacy Policy, and you agree that all previous versions of the
        Privacy Policy are superseded by the modified version.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">11. Acceptance</h2>
      <p className="mb-4">
        By using BizVibez’s website, you signify your acceptance of this Policy.
      </p>
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        12. How to Contact Us
      </h2>
      <p className="mb-4">
        If you have any questions or comments regarding our privacy practices,
        you may opt to contact us via https://bizvibez.com/contact.
      </p>
    </div>
  );
}
